webserver:
  port: 10110
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  port: 10118

bigtable:
  generate-schema: true
  emulator: true
  host: localhost
  port: 9035
  project-id: my-project
  instance-id: my-instance
  credential-provider: default
  credentials:
    service-account:
      path: /conf/dapla-catalog-bigtable-test.json
    default:
    compute-engine:

auth-service:
  host: localhost
  port: 10108
