webserver:
  port: 10110
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:25432/catalog"
    username: "catalog"
    password: "catalog"
  statements:
    ping: "SELECT 0"

flyway:
  url: jdbc:postgresql://localhost:25432/catalog
  user: catalog
  password: catalog
  connect-retries: 120

health:
  readiness:
    idle-timeout: 2000

auth-service:
  host: localhost
  port: 10108

tracing:
  enabled: true
  service: catalog
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false

pubsub:
  enabled: true
  admin: true
  use-emulator: true
  emulator:
    host: localhost
    port: 8538
  credential-provider: emulator
  credentials:
    service-account:
      path: secret/my-service-account-key.json
    compute-engine:
    emulator:
    default:
  upstream:
    projectId: dapla
    topic: catalog-1
    subscription: catalog-dev

catalogds:
  bypass-validation: true
  format: PKCS12
  keystore: secret/metadata-verifier_keystore.p12
  keyAlias: dataAccessCertificate
  password: changeit
  algorithm: SHA256withRSA