webserver:
  port: 10110
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  host: 0.0.0.0
  port: 10118

pgpool:
  connect-options:
    port: 25432
    host: localhost
    database: catalog
    user: catalog
    password: catalog
  pool-options:
    max-size: 5

flyway:
  url: jdbc:postgresql://localhost:25432/catalog
  user: catalog
  password: catalog

init:
  db-connectivity-attempts: 120

health:
  readiness:
    idle-timeout: 2000

auth-service:
  host: localhost
  port: 10108

tracing:
  enabled: true
  service: catalog
  sampler-type: const
  sampler-param: 1
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/health"
      enabled: false

pubsub:
  enabled: true
  use-emulator: true
  emulator:
    host: localhost
    port: 8538
  credential-provider: emulator
  credentials:
    service-account:
      path: secret/my-service-account-key.json
    compute-engine:
    emulator:
    default:
  upstream:
    projectId: dapla
    topic: catalog-1
    subscription: catalog-dev
