webserver:
  port: 8070
  host: "0.0.0.0"

grpcserver:
  port: 1408

bigtable:
  generate-schema: true
  emulator: true
  host: localhost
  port: 9035
  project-id: my-project
  instance-id: my-instance
  table-id: dataset
  column-family: document
  service-account:
    path: secret/bigtable_sa_key.json
